server:
  port: 9096

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    hikari:
      pool-name: pesapap-api-pool
      maximum-pool-size: 200
      allow-pool-suspension: true
  security:
    user:
      name: pesapap-api
      password: pesap1234
  sql:
    init:
      platform: h2
